FROM eclipse-mosquitto:2.0

# Copy custom Mosquitto config that enables both TCP and WebSocket listeners
COPY mosquitto.conf /mosquitto/config/mosquitto.conf

EXPOSE 1883
EXPOSE 9001

CMD ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
