FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY core/ ./core/
COPY sensor.proto .
COPY protocol/service_grpc.py .

RUN python -m grpc_tools.protoc \
      -I. \
      --python_out=. \
      --grpc_python_out=. \
      sensor.proto

EXPOSE 50051

CMD ["python", "service_grpc.py"]