FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY core/ ./core/
COPY service_websocket.py .

EXPOSE 8003   
EXPOSE 8080   

CMD ["python", "service_websocket.py"]
