FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY core/ ./core/
COPY sensor_pb2.py .
COPY sensor_pb2_grpc.py .
COPY gateway.py .

EXPOSE 8004

CMD ["python", "gateway.py"]