FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY shared/ ./shared/
COPY service_http1.py .

EXPOSE 8001

CMD ["python", "service_http1.py"]
